name: Configure VLF Cron

on:
  push:
    branches:
      - main  # Adjust if using a different default branch
  workflow_dispatch:

jobs:
  setup-cron:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync project to persistent directory
        run: |
          TARGET_DIR="$HOME/stferics_logger"
          mkdir -p "$TARGET_DIR"
          rsync -a --delete "${GITHUB_WORKSPACE}/" "$TARGET_DIR/"

      - name: Set up Python environment
        run: |
          TARGET_DIR="$HOME/stferics_logger"
          VENV_DIR="$TARGET_DIR/venv"
          python3 -m venv "$VENV_DIR"
          source "$VENV_DIR/bin/activate"
          pip install --upgrade pip
          pip install -r "$TARGET_DIR/requirements.txt"

      - name: Configure nightly 12h recorder cron
        run: |
          TARGET_DIR="$HOME/stferics_logger"
          VENV_DIR="$TARGET_DIR/venv"
          LOG_DIR="$TARGET_DIR/logs"
          mkdir -p "$LOG_DIR"
          # Run once daily at 18:00 local time; script records until 06:00
          CRON_CMD="0 19 * * * cd $TARGET_DIR && $VENV_DIR/bin/python vlf_cron_sferic_logger.py >> $LOG_DIR/vlf.log 2>&1"

          TMP_FILE=$(mktemp)
          if crontab -l >/dev/null 2>&1; then
            crontab -l | grep -v "vlf_cron_sferic_logger.py" > "$TMP_FILE" || true
          else
            : > "$TMP_FILE"
          fi
          echo "$CRON_CMD" >> "$TMP_FILE"
          crontab "$TMP_FILE"
          rm "$TMP_FILE"
